# Modules
- color: "fbca04"
  description: "This issue or pull request is related to ecr-registry module."
  name: ":floppy_disk: ecr-registry"
- color: "fbca04"
  description: "This issue or pull request is related to ecr-repository module."
  name: ":floppy_disk: ecr-repository"
- color: "fbca04"
  description: "This issue or pull request is related to eks-access-entry module."
  name: ":floppy_disk: eks-access-entry"
- color: "fbca04"
  description: "This issue or pull request is related to eks-addon module."
  name: ":floppy_disk: eks-addon"
- color: "fbca04"
  description: "This issue or pull request is related to eks-aws-auth module."
  name: ":floppy_disk: eks-aws-auth"
- color: "fbca04"
  description: "This issue or pull request is related to eks-cluster module."
  name: ":floppy_disk: eks-cluster"
- color: "fbca04"
  description: "This issue or pull request is related to eks-fargate-profile module."
  name: ":floppy_disk: eks-fargate-profile"
- color: "fbca04"
  description: "This issue or pull request is related to eks-iam-access module."
  name: ":floppy_disk: eks-iam-access"
- color: "fbca04"
  description: "This issue or pull request is related to eks-max-pods module."
  name: ":floppy_disk: eks-max-pods"
- color: "fbca04"
  description: "This issue or pull request is related to eks-node-group module."
  name: ":floppy_disk: eks-node-group"
- color: "fbca04"
  description: "This issue or pull request is related to eks-official-image module."
  name: ":floppy_disk: eks-official-image"
