# Warning
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "ee0701"
  description: "Categorize vulnerability reports."
  name: ":warning: vulnerability"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"

# Cancel
- color: "b60205"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "b60205"
  description: "This will not be worked on."
  name: ":pray: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"

# Modules
- color: "fbca04"
  description: "This issue or pull request is related to ecr-registry module."
  name: ":floppy_disk: ecr-registry"
- color: "fbca04"
  description: "This issue or pull request is related to ecr-repository module."
  name: ":floppy_disk: ecr-repository"
- color: "fbca04"
  description: "This issue or pull request is related to eks-addon module."
  name: ":floppy_disk: eks-addon"
- color: "fbca04"
  description: "This issue or pull request is related to eks-aws-auth module."
  name: ":floppy_disk: eks-aws-auth"
- color: "fbca04"
  description: "This issue or pull request is related to eks-cluster module."
  name: ":floppy_disk: eks-cluster"
- color: "fbca04"
  description: "This issue or pull request is related to eks-fargate-profile module."
  name: ":floppy_disk: eks-fargate-profile"
- color: "fbca04"
  description: "This issue or pull request is related to eks-iam-access module."
  name: ":floppy_disk: eks-iam-access"
- color: "fbca04"
  description: "This issue or pull request is related to eks-max-pods module."
  name: ":floppy_disk: eks-max-pods"
- color: "fbca04"
  description: "This issue or pull request is related to eks-node-group module."
  name: ":floppy_disk: eks-node-group"
